remote_theme: minima
plugins:
- jekyll-remote-theme
- jekyll-menus

title: Astronomer Airflow DAG Authoring Certification 
description: Course Notes


skin: auto
social_links:
  - { platform: linkedin,  user_url: "https://www.linkedin.com/in/ovimihai/" }
